### ISSUE TITLE
How to use credentials?

### ISSUE THREAD

**Issue by smyth64** [partoutx/connect-arangodb-session#1]
How can I use them in this module?

**Comment by gbevan** [comment]
the module simply passes the url of the database to [arangojs](https://github.com/arangodb/arangojs), you can embed credentials in the url - there is an example on arangojs's git page:
e.g.
```
// Using a complex connection string with authentication
let host = process.env.ARANGODB_HOST;
let port = process.env.ARANGODB_PORT;
let database = process.env.ARANGODB_DB;
let username = process.env.ARANGODB_USERNAME;
let password = process.env.ARANGODB_PASSWORD;
let db = arangojs({
  url: `http://${username}:${password}@${host}:${port}`,
  databaseName: database
});

// Or using a fully qualified URL containing the database path
let db = arangojs({
  url: `http://${username}:${password}@${host}:${port}/_db/${database}`,
  databaseName: false // don't automatically append database path to URL
});
```
There is also a fork where someone is adding basic authentication [here](https://github.com/webforgeeu/connect-arangodb-session/commit/8824968854b332f3d319f6aa6adf4ce1bc2d8b52)

**Comment by nkanand4** [comment]
@smith64fx I do not know if your problem is similar to mine or not but I realized if you are using credentials which do not have access to _system database, this does not work. I had to patch index.js on line #65 to pass the database name, https://github.com/partoutx/connect-arangodb-session/blob/0.1.0-alpha1/index.js#L65
